version: '3.8'

services:
  credit-score-api:
    build: .
    container_name: bati-bank-api
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns